Use logback and offer structured logging options
- install logback-classic and exclude conflicting transitive
  dependencies in pom.xml

- add a default logback.xml file

- update the README to link to the logback documentation and point
  out how and where to enable structured logging

- add `test.Dockerfile` to build a deployable docker image from
  a locally built fatjar

diff --git a/src/main/bin/clickhouse-jdbc-bridge b/src/main/bin/clickhouse-jdbc-bridge
--- a/src/main/bin/clickhouse-jdbc-bridge
+++ b/src/main/bin/clickhouse-jdbc-bridge
@@ -25,45 +25,45 @@ INIT_SCRIPT="/etc/clickhouse-jdbc-bridge/set-env.sh"
 JAVA_CMD="java"
 
 init_env() {
-    if [ -f $INIT_SCRIPT ]; then
-        echo "Executing [$INIT_SCRIPT] to set environment variables..."
-        . $INIT_SCRIPT
-    else
-        echo "[$INIT_SCRIPT] is not found, will use default environment variables"
-    fi
+  if [ -f $INIT_SCRIPT ]; then
+    echo "Executing [$INIT_SCRIPT] to set environment variables..."
+    . $INIT_SCRIPT
+  else
+    echo "[$INIT_SCRIPT] is not found, will use default environment variables"
+  fi
 
-    # check if we have JRE
-    if [ -n "$JAVA_HOME" ] && [ -x "$JAVA_HOME/bin/java" ];  then
-        JAVA_CMD="$JAVA_HOME/bin/java"
-    elif ! type -p java > /dev/null; then
-        echo "ERROR: Java needs to be installed first"
-        exit 1
-    fi
+  # check if we have JRE
+  if [ -n "$JAVA_HOME" ] && [ -x "$JAVA_HOME/bin/java" ]; then
+    JAVA_CMD="$JAVA_HOME/bin/java"
+  elif ! type -p java >/dev/null; then
+    echo "ERROR: Java needs to be installed first"
+    exit 1
+  fi
 }
 
 start_server() {
-    # override below environment variables as needed in $INIT_SCRIPT
-    : ${APP_PACKAGE:="/usr/local/lib/java/clickhouse-jdbc-bridge-shaded.jar"}
-    : ${JVM_ARGS:="-Xmx512m"}
-    : ${WORK_DIRECTORY:=$(dirname "$INIT_SCRIPT")}
+  # override below environment variables as needed in $INIT_SCRIPT
+  : ${APP_PACKAGE:="/usr/local/lib/java/clickhouse-jdbc-bridge-shaded.jar"}
+  : ${JVM_ARGS:="-Xmx512m"}
+  : ${WORK_DIRECTORY:=$(dirname "$INIT_SCRIPT")}
 
-    # kill server if it's running
-    kill -9 $(ps -ef | grep java | grep "$APP_PACKAGE" | awk '{print $2}') 2>/dev/null || true
+  # kill server if it's running
+  kill -9 $(ps -ef | grep java | grep "$APP_PACKAGE" | awk '{print $2}') 2>/dev/null || true
 
-    if [ ! -f "$APP_PACKAGE" ]; then
-        echo "ERROR: ClickHouse JDBC Bridge could not start because [$APP_PACKAGE] is missing"
-        exit 1
-    fi
+  if [ ! -f "$APP_PACKAGE" ]; then
+    echo "ERROR: ClickHouse JDBC Bridge could not start because [$APP_PACKAGE] is missing"
+    exit 1
+  fi
 
-    if [ ! -d "$WORK_DIRECTORY" ]; then
-        echo "WARN: Work directory [$WORK_DIRECTORY] does not exist"
-        WORK_DIRECTORY=$(dirname "$INIT_SCRIPT")
-    fi
+  if [ ! -d "$WORK_DIRECTORY" ]; then
+    echo "WARN: Work directory [$WORK_DIRECTORY] does not exist"
+    WORK_DIRECTORY=$(dirname "$INIT_SCRIPT")
+  fi
 
-    echo "Work directory is set to [$WORK_DIRECTORY]"
-    cd "$WORK_DIRECTORY"
-    java $JVM_ARGS -Djava.util.logging.config.file=$WORK_DIRECTORY/logging.properties \
-        -Duser.dir="$WORK_DIRECTORY" -jar "$APP_PACKAGE"
+  echo "Work directory is set to [$WORK_DIRECTORY]"
+  cd "$WORK_DIRECTORY"
+  java $JVM_ARGS -Dlogback.configurationFile=$WORK_DIRECTORY/logback.xml \
+    -Duser.dir="$WORK_DIRECTORY" -jar "$APP_PACKAGE"
 }
 
 init_env
